Added useOutsideClick hook to NavBarDropdown
varianter/vibes pull request #227
Opened 2023-10-26 13:27 UTC by yelodevopsi

2023-10-30 10:08 UTC, jonasbjoralt requested changes
Liker veldig godt forbedringene i useFilteredConsultants, disse var veldig ettertraktet. Her fjerner du mye kode og hooken ser laaaangt bedre ut. Så dette må vi jo få inn på et vis. 



Men resten av endringene er jeg veldig mye mer usikker på. Ser her at vi investerer mer i mobilvisning, og med piksel-basert layout. Samtidig er det ikke tatt noe overordnet beslutning på å støtte mobilvisning (unntatt for variantdagen). 

Så med dette får vi flere hooks å vedlikeholde, for å støtte noe som kanskje ikke skal støttes. 
Samtidig forstår jeg godt at det var lett å tro at "nå skal vi støtte mobil", siden vi jobbet myye med det forrige uke. 

På et sidespor kan det du fikser med useScreenSize o.l. løses enklere via CSS. 

Uansett - fjern endringene relatert til UI-bugs, men behold gjerne opprydninga i useFiltered-hooken :)

2023-10-30 10:24 UTC, yelodevopsi commented on frontend/src/hooks/useFilteredConsultants.ts
> +}
Nice tip! Ja, var selv i tanken om dette, men kom ikke så langt bare.
Legger inn en forbedring nå

2023-10-30 10:35 UTC, yelodevopsi commented
> Liker veldig godt forbedringene i useFilteredConsultants, disse var veldig ettertraktet. Her fjerner du mye kode og hooken ser laaaangt bedre ut. Så dette må vi jo få inn på et vis.
> 
> Men resten av endringene er jeg veldig mye mer usikker på. Ser her at vi investerer mer i mobilvisning, og med piksel-basert layout. Samtidig er det ikke tatt noe overordnet beslutning på å støtte mobilvisning (unntatt for variantdagen).
> 
> Så med dette får vi flere hooks å vedlikeholde, for å støtte noe som kanskje ikke skal støttes. Samtidig forstår jeg godt at det var lett å tro at "nå skal vi støtte mobil", siden vi jobbet myye med det forrige uke.
> 
> På et sidespor kan det du fikser med useScreenSize o.l. løses enklere via CSS.
> 
> Uansett - fjern endringene relatert til UI-bugs, men behold gjerne opprydninga i useFiltered-hooken :)

Tror du mistolker litt. Det er ikke primært mobilvisning det er snakk om her, men funksjonaliteten for å "klikke utenfor" en container jeg har laget en hook for. Om du har andre forslag til denne hooken/alternativer, så kom gjerne med dette da det brukes på veldig mange steder. 

Vil også selv si at den er ganske kort og ren med enkel bruk a "ref" for å knytte til event-listener, så jeg ønsker vi beholder den da jeg kommer til å bruke den fremover uansett.

useScreenSize hooken kan vi diskutere ja, eller forbedre iaf, om vi ønsker det skal tangere bedre med "sm, lg, xl..." verdiene vi har konfigurert. Men det behøves logikk for å finne ut om vi er i mobilvisning eller ikke. Det stemmer jeg for at vi beholder.

Vi må gjerne bygge videre på med #230 Refactor tasken for å standardisere enda mer, men fint om layout-størrelsene kan ta basis i screens.config.ts const'ene som er definert.

Annen renaming eller struktur er jeg veldig for å ordne på! 👍

2023-10-30 10:37 UTC, yelodevopsi commented on frontend/src/app/page.tsx
> +    <ul className="h-[calc(100vh-52px)] overflow-auto flex items-center justify-center gap-4">
Reverterte denne nå 👍

2023-10-30 11:29 UTC, yelodevopsi commented on frontend/src/hooks/useFilteredConsultants.ts
> +}
Da har jeg oppdatert med ny rewrite av toggleFilterFromString...
Ikke helt fornøyd med den, men tenker er mer strukturert nå.

2023-10-31 07:08 UTC, jonasbjoralt commented
> > Liker veldig godt forbedringene i useFilteredConsultants, disse var veldig ettertraktet. Her fjerner du mye kode og hooken ser laaaangt bedre ut. Så dette må vi jo få inn på et vis.
> > Men resten av endringene er jeg veldig mye mer usikker på. Ser her at vi investerer mer i mobilvisning, og med piksel-basert layout. Samtidig er det ikke tatt noe overordnet beslutning på å støtte mobilvisning (unntatt for variantdagen).
> > Så med dette får vi flere hooks å vedlikeholde, for å støtte noe som kanskje ikke skal støttes. Samtidig forstår jeg godt at det var lett å tro at "nå skal vi støtte mobil", siden vi jobbet myye med det forrige uke.
> > På et sidespor kan det du fikser med useScreenSize o.l. løses enklere via CSS.
> > Uansett - fjern endringene relatert til UI-bugs, men behold gjerne opprydninga i useFiltered-hooken :)
> 
> Tror du mistolker litt. Det er ikke primært mobilvisning det er snakk om her, men funksjonaliteten for å "klikke utenfor" en container jeg har laget en hook for. Om du har andre forslag til denne hooken/alternativer, så kom gjerne med dette da det vil brukes på mange steder.
> 
> Vil også selv si at den er ganske kort og ren med enkel bruk a "ref" for å knytte til event-listener, så jeg ønsker vi beholder den da jeg kommer til å bruke den fremover uansett.
> 
> useScreenSize hooken kan vi diskutere ja, eller forbedre iaf, om vi ønsker det skal tangere bedre med "sm, lg, xl..." verdiene vi har konfigurert. Men det behøves logikk for å finne ut om vi er i mobilvisning eller ikke. Det stemmer jeg for at vi beholder.
> 
> Vi må gjerne bygge videre på med #230 Refactor tasken for å standardisere enda mer, men fint om layout-størrelsene kan ta basis i screens.config.ts const'ene som er definert.
> 
> Annen renaming eller struktur er jeg veldig for å ordne på! 👍

Tror kanskje vi snakker litt forbi hverandre her. Om du har tid, la oss heller ringe eller prates irl :) 

Koden her er ganske bra skrevet og løser problemet på en god måte. useRef er helt rett å bruke og jeg har lite å utsette der. 

Problemet er bare at jeg ikke tror dette skal være en feature på skjermene vi skal støtte fremover, og at vi derfor ikke trenger dette nå. Mer kode = mer å vedlikeholde, og da er det dessverre best å "kaste" dette. Selv om det selvfølgelig virker veldig kjipt siden du har lagt en ganske god innsats i dette.

2023-10-31 07:48 UTC, jonasbjoralt approved these changes
Er ikke helt overbevist om at å bruke en klasse er det beste løsninga, men det funka ganske ålreit enn så lenge. 

Godkjent :)

2023-10-31 08:02 UTC, merged

2023-10-31 08:03 UTC, yelodevopsi commented
> Er ikke helt overbevist om at å bruke en klasse er det beste løsninga, men det funka ganske ålreit enn så lenge.
> 
> Godkjent :)

Oh, I know! Men lekte meg litt rundt for å sjekke hvordan dette kunne optimaliseres, og for min egen psyke så syns jeg en klasse virket naiz. Too much backend consumed..